/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cork.glb -T -t 
Files: .\cork.glb [109.31KB] > C:\Users\HP\Documents\projects\korvo\public\models\cork-transformed.glb [13.06KB] (88%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['oryzo-1-344b-a0b']: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cork-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['oryzo-1-344b-a0b'].geometry} material={nodes['oryzo-1-344b-a0b'].material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cork-transformed.glb')
