/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\coffee_cup.glb -T -t 
Files: .\coffee_cup.glb [2.93MB] > C:\Users\HP\Documents\projects\korvo\public\models\coffee_cup-transformed.glb [251.06KB] (91%)
Author: Dokazvo (https://sketchfab.com/dokazvo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-gameready-free-dl-a178cea47a9c471e9a62b0ef6ba9f53c
Title: Coffee cup (GAMEREADY, FREE DL)
*/

import * as THREE from 'three'
import {type JSX} from 'react'
import {useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
	nodes: {
		Coffee_cup_low_Material_0: THREE.Mesh
	}
	materials: {
		Material: THREE.MeshStandardMaterial
	}
	animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
	const {nodes, materials} = useGLTF('/coffee_cup-transformed.glb') as unknown as GLTFResult
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Coffee_cup_low_Material_0.geometry} material={materials.Material}/>
		</group>
	)
}

useGLTF.preload('models/coffee_cup-transformed.glb')
