/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cork.glb -T -t 
Files: .\cork.glb [109.31KB] > C:\Users\HP\Documents\projects\korvo\public\models\cork-transformed.glb [13.06KB] (88%)
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import {useGLTF, useTexture} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    ['oryzo-1-344b-a0b']: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export default function Cork(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/cork-transformed.glb') as unknown as GLTFResult
  
  const [diffuse, roughness, normal] = useTexture([
    '/textures/cork/diffuse.jpg',
    '/textures/cork/roughness.jpg',
    '/textures/cork/normal.jpg',
  ])
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['oryzo-1-344b-a0b'].geometry} material={nodes['oryzo-1-344b-a0b'].material} rotation={[Math.PI, 0, 0]}>
        <meshStandardMaterial
            map={diffuse}
            roughnessMap={roughness}
            normalMap={normal}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/cork-transformed.glb')
