/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\korvo-cork.glb -T -t 
Files: .\korvo-cork.glb [1.72MB] > C:\Users\HP\Documents\projects\korvo\public\models\korvo-cork-transformed.glb [125.72KB] (93%)
*/

import * as THREE from 'three'
import {forwardRef, type JSX} from 'react'
import {useGLTF, useTexture} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
	nodes: {
		korvo: THREE.Mesh
	}
	materials: object
	animations: GLTFAction[]
}

const Cork = forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
	const {nodes} = useGLTF('/models/korvo-cork-transformed.glb') as unknown as GLTFResult
	const [diffuse, roughness, normal] = useTexture([
		'/textures/cork/diffuse.jpg',
		'/textures/cork/roughness.jpg',
		'/textures/cork/normal.jpg',
	])
	
	return (
		<group {...props} ref={ref} dispose={null}>
			<mesh geometry={nodes.korvo.geometry} material={nodes.korvo.material} rotation={[Math.PI, 0, 0]}>
				<meshStandardMaterial
					map={diffuse}
					roughnessMap={roughness}
					normalMap={normal}
				/>
			</mesh>
		</group>
	)
})

export default Cork;

useGLTF.preload('/models/korvo-cork-transformed.glb')
